# Alternative GNU Make project makefile autogenerated by Premake

ifndef config
  config=debug_x86_64
endif

ifndef verbose
  SILENT = @
endif

.PHONY: clean prebuild

SHELLTYPE := posix
ifeq (.exe,$(findstring .exe,$(ComSpec)))
	SHELLTYPE := msdos
endif

# Configurations
# #############################################

RESCOMP = windres
INCLUDES += -Ick -I. -Icwalk -IcJSON -Ilua/src
FORCE_INCLUDE +=
ALL_CPPFLAGS += $(CPPFLAGS) -MD -MP $(DEFINES) $(INCLUDES)
ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
LINKCMD = $(CC) -o "$@" $(OBJECTS) $(RESOURCES) $(ALL_LDFLAGS) $(LIBS)
define PREBUILDCMDS
endef
define PRELINKCMDS
endef
define POSTBUILDCMDS
endef

ifeq ($(config),debug_x86_32)
TARGETDIR = bin/Debug-linux-x86/ck
TARGET = $(TARGETDIR)/ck
OBJDIR = obj/Debug-linux-x86/ck
DEFINES += -D_DEBUG
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m32 -Werror -ffloat-store -Og -g -std=gnu11
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m32 -Werror -ffloat-store -Og -g -fsanitize=address
LIBS += sbin/Debug-linux-x86/cJSON/libcJSON.a sbin/Debug-linux-x86/cwalk/libcwalk.a sbin/Debug-linux-x86/lua/liblua.a sbin/Debug-linux-x86/ckmem/libckmem.a sbin/Debug-linux-x86/fflib/libfflib.a -lm
LDDEPS += sbin/Debug-linux-x86/cJSON/libcJSON.a sbin/Debug-linux-x86/cwalk/libcwalk.a sbin/Debug-linux-x86/lua/liblua.a sbin/Debug-linux-x86/ckmem/libckmem.a sbin/Debug-linux-x86/fflib/libfflib.a
ALL_LDFLAGS += $(LDFLAGS) -L/usr/lib32 -m32

else ifeq ($(config),debug_x86_64)
TARGETDIR = bin/Debug-linux-x86_64/ck
TARGET = $(TARGETDIR)/ck
OBJDIR = obj/Debug-linux-x86_64/ck
DEFINES += -D_DEBUG
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -Werror -ffloat-store -Og -g -std=gnu11
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -Werror -ffloat-store -Og -g -fsanitize=address
LIBS += sbin/Debug-linux-x86_64/cJSON/libcJSON.a sbin/Debug-linux-x86_64/cwalk/libcwalk.a sbin/Debug-linux-x86_64/lua/liblua.a sbin/Debug-linux-x86_64/ckmem/libckmem.a sbin/Debug-linux-x86_64/fflib/libfflib.a -lm
LDDEPS += sbin/Debug-linux-x86_64/cJSON/libcJSON.a sbin/Debug-linux-x86_64/cwalk/libcwalk.a sbin/Debug-linux-x86_64/lua/liblua.a sbin/Debug-linux-x86_64/ckmem/libckmem.a sbin/Debug-linux-x86_64/fflib/libfflib.a
ALL_LDFLAGS += $(LDFLAGS) -L/usr/lib64 -m64

else ifeq ($(config),release_x86_32)
TARGETDIR = bin/Release-linux-x86/ck
TARGET = $(TARGETDIR)/ck
OBJDIR = obj/Release-linux-x86/ck
DEFINES +=
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m32 -Werror -flto -ffloat-store -fomit-frame-pointer -O3 -std=gnu11
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m32 -Werror -flto -ffloat-store -fomit-frame-pointer -O3 -fno-stack-protector
LIBS += sbin/Release-linux-x86/cJSON/libcJSON.a sbin/Release-linux-x86/cwalk/libcwalk.a sbin/Release-linux-x86/lua/liblua.a sbin/Release-linux-x86/ckmem/libckmem.a sbin/Release-linux-x86/fflib/libfflib.a -lm
LDDEPS += sbin/Release-linux-x86/cJSON/libcJSON.a sbin/Release-linux-x86/cwalk/libcwalk.a sbin/Release-linux-x86/lua/liblua.a sbin/Release-linux-x86/ckmem/libckmem.a sbin/Release-linux-x86/fflib/libfflib.a
ALL_LDFLAGS += $(LDFLAGS) -L/usr/lib32 -m32 -flto -s

else ifeq ($(config),release_x86_64)
TARGETDIR = bin/Release-linux-x86_64/ck
TARGET = $(TARGETDIR)/ck
OBJDIR = obj/Release-linux-x86_64/ck
DEFINES +=
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -Werror -flto -ffloat-store -fomit-frame-pointer -O3 -std=gnu11
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -Werror -flto -ffloat-store -fomit-frame-pointer -O3 -fno-stack-protector
LIBS += sbin/Release-linux-x86_64/cJSON/libcJSON.a sbin/Release-linux-x86_64/cwalk/libcwalk.a sbin/Release-linux-x86_64/lua/liblua.a sbin/Release-linux-x86_64/ckmem/libckmem.a sbin/Release-linux-x86_64/fflib/libfflib.a -lm
LDDEPS += sbin/Release-linux-x86_64/cJSON/libcJSON.a sbin/Release-linux-x86_64/cwalk/libcwalk.a sbin/Release-linux-x86_64/lua/liblua.a sbin/Release-linux-x86_64/ckmem/libckmem.a sbin/Release-linux-x86_64/fflib/libfflib.a
ALL_LDFLAGS += $(LDFLAGS) -L/usr/lib64 -m64 -flto -s

endif

# Per File Configurations
# #############################################


# File sets
# #############################################

GENERATED :=
OBJECTS :=

GENERATED += $(OBJDIR)/Configs.o
GENERATED += $(OBJDIR)/Diagnostics.o
GENERATED += $(OBJDIR)/Driver.o
GENERATED += $(OBJDIR)/Expression.o
GENERATED += $(OBJDIR)/FileIO.o
GENERATED += $(OBJDIR)/Food.o
GENERATED += $(OBJDIR)/Lex.o
GENERATED += $(OBJDIR)/Main.o
GENERATED += $(OBJDIR)/Parser.o
GENERATED += $(OBJDIR)/ParserExpressions.o
GENERATED += $(OBJDIR)/ParserStatements.o
GENERATED += $(OBJDIR)/ParserTypes.o
GENERATED += $(OBJDIR)/Semantics.o
GENERATED += $(OBJDIR)/Time.o
OBJECTS += $(OBJDIR)/Configs.o
OBJECTS += $(OBJDIR)/Diagnostics.o
OBJECTS += $(OBJDIR)/Driver.o
OBJECTS += $(OBJDIR)/Expression.o
OBJECTS += $(OBJDIR)/FileIO.o
OBJECTS += $(OBJDIR)/Food.o
OBJECTS += $(OBJDIR)/Lex.o
OBJECTS += $(OBJDIR)/Main.o
OBJECTS += $(OBJDIR)/Parser.o
OBJECTS += $(OBJDIR)/ParserExpressions.o
OBJECTS += $(OBJDIR)/ParserStatements.o
OBJECTS += $(OBJDIR)/ParserTypes.o
OBJECTS += $(OBJDIR)/Semantics.o
OBJECTS += $(OBJDIR)/Time.o

# Rules
# #############################################

all: $(TARGET)
	@:

$(TARGET): $(GENERATED) $(OBJECTS) $(LDDEPS) | $(TARGETDIR)
	$(PRELINKCMDS)
	@echo Linking ck
	$(SILENT) $(LINKCMD)
	$(POSTBUILDCMDS)

$(TARGETDIR):
	@echo Creating $(TARGETDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(TARGETDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(TARGETDIR))
endif

$(OBJDIR):
	@echo Creating $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(OBJDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(OBJDIR))
endif

clean:
	@echo Cleaning ck
ifeq (posix,$(SHELLTYPE))
	$(SILENT) rm -f  $(TARGET)
	$(SILENT) rm -rf $(GENERATED)
	$(SILENT) rm -rf $(OBJDIR)
else
	$(SILENT) if exist $(subst /,\\,$(TARGET)) del $(subst /,\\,$(TARGET))
	$(SILENT) if exist $(subst /,\\,$(GENERATED)) del /s /q $(subst /,\\,$(GENERATED))
	$(SILENT) if exist $(subst /,\\,$(OBJDIR)) rmdir /s /q $(subst /,\\,$(OBJDIR))
endif

prebuild: | $(OBJDIR)
	$(PREBUILDCMDS)

ifneq (,$(PCH))
$(OBJECTS): $(GCH) | $(PCH_PLACEHOLDER)
$(GCH): $(PCH) | prebuild
	@echo $(notdir $<)
	$(SILENT) $(CC) -x c-header $(ALL_CFLAGS) -o "$@" -MF "$(@:%.gch=%.d)" -c "$<"
$(PCH_PLACEHOLDER): $(GCH) | $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) touch "$@"
else
	$(SILENT) echo $null >> "$@"
endif
else
$(OBJECTS): | prebuild
endif


# File Rules
# #############################################

$(OBJDIR)/Configs.o: ck/src/Configs.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Diagnostics.o: ck/src/Diagnostics.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Driver.o: ck/src/Driver.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/FileIO.o: ck/src/FileIO.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Food.o: ck/src/Food.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Main.o: ck/src/Main.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Expression.o: ck/src/Syntax/Expression.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Lex.o: ck/src/Syntax/Lex.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Parser.o: ck/src/Syntax/Parser.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ParserExpressions.o: ck/src/Syntax/ParserExpressions.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ParserStatements.o: ck/src/Syntax/ParserStatements.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ParserTypes.o: ck/src/Syntax/ParserTypes.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Semantics.o: ck/src/Syntax/Semantics.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Time.o: ck/src/Util/Time.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"

-include $(OBJECTS:%.o=%.d)
ifneq (,$(PCH))
  -include $(PCH_PLACEHOLDER).d
endif