CK_EXPRESSION_DUMMY = 0
CK_EXPRESSION_REFERENCE = 1
CK_EXPRESSION_LITERAL = 2
CK_EXPRESSION_TYPEOF = 3
CK_EXPRESSION_POSTFIX_INC = 4
CK_EXPRESSION_POSTFIX_DEC = 5
CK_EXPRESSION_FUNCCALL = 6
CK_EXPRESSION_SUBSCRIPT = 7
CK_EXPRESSION_MEMBER_ACCESS = 8
CK_EXPRESSION_POINTER_MEMBER_ACCESS = 9
CK_EXPRESSION_PREFIX_INC = 10
CK_EXPRESSION_PREFIX_DEC = 11
CK_EXPRESSION_UNARY_PLUS = 12
CK_EXPRESSION_UNARY_MINUS = 13
CK_EXPRESSION_LOGICAL_NOT = 14
CK_EXPRESSION_BITWISE_NOT = 15
CK_EXPRESSION_CAST = 16
CK_EXPRESSION_DEREFERENCE = 17
CK_EXPRESSION_OPAQUE_ADDRESS_OF = 18
CK_EXPRESSION_ADDRESS_OF = 19
CK_EXPRESSION_MUL = 20
CK_EXPRESSION_DIV = 21
CK_EXPRESSION_MOD = 22
CK_EXPRESSION_ADD = 23
CK_EXPRESSION_SUB = 24
CK_EXPRESSION_LEFT_SHIFT = 25
CK_EXPRESSION_RIGHT_SHIFT = 26
CK_EXPRESSION_LOWER = 27
CK_EXPRESSION_LOWER_EQUAL = 28
CK_EXPRESSION_GREATER = 29
CK_EXPRESSION_GREATER_EQUAL = 30
CK_EXPRESSION_EQUAL = 31
CK_EXPRESSION_NOT_EQUAL = 32
CK_EXPRESSION_BITWISE_AND = 33
CK_EXPRESSION_BITWISE_XOR = 34
CK_EXPRESSION_BITWISE_OR = 35
CK_EXPRESSION_LOGICAL_AND = 36
CK_EXPRESSION_LOGICAL_OR = 37
CK_EXPRESSION_CONDITIONAL = 38
CK_EXPRESSION_ASSIGN = 39
CK_EXPRESSION_ASSIGN_SUM = 40
CK_EXPRESSION_ASSIGN_DIFF = 41
CK_EXPRESSION_ASSIGN_PRODUCT = 42
CK_EXPRESSION_ASSIGN_QUOTIENT = 43
CK_EXPRESSION_ASSIGN_REMAINDER = 44
CK_EXPRESSION_ASSIGN_LEFT_SHIFT = 45
CK_EXPRESSION_ASSIGN_RIGHT_SHIFT = 46
CK_EXPRESSION_ASSIGN_AND = 47
CK_EXPRESSION_ASSIGN_XOR = 48
CK_EXPRESSION_ASSIGN_OR = 49

CK_TYPE_VOID = 0
CK_TYPE_BOOL = 1
CK_TYPE_I8 = 2
CK_FOOD_U8 = 3
CK_FOOD_I16 = 4
CK_FOOD_U16 = 5
CK_FOOD_F16 = 6
CK_FOOD_I32 = 7
CK_FOOD_U32 = 8
CK_FOOD_ENUM = 9
CK_FOOD_F32 = 10
CK_FOOD_I64 = 11
CK_FOOD_U64 = 12
CK_FOOD_F64 = 13
CK_FOOD_FUNCPOINTER = 14
CK_FOOD_POINTER = 15
CK_FOOD_REFERENCE = 16
CK_FOOD_ARRAY = 17
CK_FOOD_STRING = 18
CK_FOOD_USER = 19

CkType = { base = 0, child = nil, extra = nil }

function CkType:new(o, base, child, extra)
	o = o or {}
	setmetatable(o, self)
	self.__index = self
	self.base = base or 0
	self.child = child
	self.extra = extra
	return o
end

CkExpression = {
	kind = 0,
	value = nil,
	left = nil,
	right = nil,
	extra = nil,
	type = nil
}

function CkExpression:new(o, kind, value, left, right, extra, type)
	o = o or {}
	setmetatable(o, self)
	self.__index = self
	self.value = value
	self.left = left
	self.right = right
	self.extra = extra
	self.type = type
	return o
end

CkVariable = {
	name = nil,
	type = nil,
	attributes = nil
}

function CkVariable:new(o, name, type, attributes)
	o = o or {}
	setmetatable(o, self)
	self.__index = self
	self.name = name
	self.type = type
	self.attributes = attributes
end
